const userData = [
  {
    projectLocation: "New Delhi",
    manualApplicationNo: "APL123456",
    bookingReceiptNo: "BRN78910",
    name: "Amit Sharma",
    fatherHusbandName: "Rajesh Sharma",
    grandFatherName: "Mohan Sharma",
    alloteeDOB: "1990-05-15",
    areaLocation1: "Sector 15",
    areaLocation2: "Near Metro Station",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110001",
    country: "India",
    email: "amit.sharma@example.com",
    mobile: "9876543210",
    stdISDCode: "+91",
    phone: "011-23456789",
    fax: "011-98765432",
    incomeTaxWardNo: "ITW-102",
    distNo: "D-45",
    panNo: "ABCDE1234F",
    aadharNo: "1234-5678-9101",
    gstin: "22ABCDE1234F1Z5",
    agentName: "Rahul Verma",
    paidAmount: "500000",
    nomineeName: "Neha Sharma",
    nomineeAddress: "Sector 10, Noida, Uttar Pradesh, India",
    documents: [
      {
        type: "allotmentLetter",
        name: "https://www.edelweissmf.com/Files/Insigths/booksummary/pdf/Book-Summary-Rich-Dad.pdf",
      },
      {
        type: "NOC",
        name: "https://www.edelweissmf.com/Files/Insigths/booksummary/pdf/Book-Summary-Rich-Dad.pdf",
      },
      {
        type: "indemnityLetter",
        name: "https://www.edelweissmf.com/Files/Insigths/booksummary/pdf/Book-Summary-Rich-Dad.pdf",
      },
      {
        type: "BBAFiles",
        name: "https://www.edelweissmf.com/Files/Insigths/booksummary/pdf/Book-Summary-Rich-Dad.pdf",
      },
      {
        type: "BBAFiles",
        name: "https://www.edelweissmf.com/Files/Insigths/booksummary/pdf/Book-Summary-Rich-Dad.pdf",
      },
      {
        type: "paymentsFiles",
        name: "https://www.edelweissmf.com/Files/Insigths/booksummary/pdf/Book-Summary-Rich-Dad.pdf",
      },
      {
        type: "paymentsFiles",
        name: "https://www.edelweissmf.com/Files/Insigths/booksummary/pdf/Book-Summary-Rich-Dad.pdf",
      },
    ],
  },
];
